color0 #0f2f2b
color1 #fd4663
color2 #67e4c2
color3 #5cbad6
color4 #d06f62
color5 #93ecd4
color6 #96d6e9
color7 #f2f3f3
color8 #617771
color9 #fd4663
color10 #67e4c2
color11 #5cbad6
color12 #d06f62
color13 #93ecd4
color14 #96d6e9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #0f2f2b
background            #0f2f2b
foreground            #f2f3f3
selection_foreground  #afb6b4
selection_background  #143e3a
active_border_color   #67e4c2
inactive_border_color #143e3a
url_color             #67e4c2
